### ISSUE TITLE
Stateless components runs but doesn't show Window page

### ISSUE THREAD

**Issue by brotherbill** [adospace/reactorui-maui#271]
**Describe the bug**
When building the sample on https://adospace.gitbook.io/mauireactor/components/state-less-components, it compiles, runs, but for "Windows Machine", no page window comes up.

**To Reproduce**
1. Download StatelessComponents.zip from https://www.adrive.com/public/MD34AB/StatelessComponents.zip
    No credentials needed.
2. Unzip and launch StatelessComponents.sln
3. Target is: Windows Machine
4. Press F5 to run
5. No Window displays.  It runs forever, unless stopped.

**Expected behavior**
I expect a tablet sized Window to display, even if empty.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows11
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] Latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
Files changed are MainPage.cs, Components/GlobalUsings.cs and Components/EntryWithLabel.cs

**Comment by adospace** [comment]
Can you put the code for the component here? please try not to attach the complete project unless it's explicitly asked: often the problem can be figured out just by looking at the code of the component/class implementing the main logic,

Thanks

**Comment by adospace** [comment]
Hi,
the problem is that EntryWithLabel has the Prop called _label: the source generator creates a method Label(..) that sets it.
The render method fails to call the Label() method derived from the component that creates the Label widget: it calls the EntryWithLabel.Label() resulting in an infinite loop:

![image](https://github.com/user-attachments/assets/f0732a1a-bc28-49d2-9231-3850603c80a9)


I've corrected the documentation, thank you for having reported it.

**Comment by brotherbill** [comment]
Even though you are the author of MauiReactor, this bug still entered the documentation.

It makes the case that the documentation should be executable with a solution ZIP file to guarantee that the ZIP file is based on working code, and that developers can go to the zip file if they make errors following the guided steps, finding their own mistakes.  

Clearly, newbies will continue to make this mistake in spite of the corrected documentation, because `string _label;` is so simple, obvious and inviting.

Some suggestions in descending order of preference:
Given that certain Property names in this context are "poison", such as _label, _entry, _button, etc.,

1. Remove the "poisonous" feature, so it doesn't bite anyone in the future.
    The reason is that this a bug waiting to pounce, a hidden bug.
    Gets rid of the bug completely at the cost of losing a "nice" feature and possibly breaking existing code.

2. In your code-generator, reject the known "poison" keywords with an exception during code-generation, giving a clear explanation to the developer.
    An alternative is for the code-generator to recognize a"poison" keyword and inject a run-time exception with a clear message, including a link to this issue.  The exception must execute before the infinite loop does.
    
3. Add documentation in this example and other more focused documentation indicating "poison" names to avoid.

4. Do nothing and have developers continue to bother you with this known issue.

The options are 1 only, 2 and 3 together, 2 only, 3 only and 4 only
